{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-10878",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://patchwork.ozlabs.org/patch/929237/",
          "name": "http://patchwork.ozlabs.org/patch/929237/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "http://patchwork.ozlabs.org/patch/929238/",
          "name": "http://patchwork.ozlabs.org/patch/929238/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.kernel.org/show_bug.cgi?id=199865",
          "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199865",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee",
          "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2",
          "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html",
          "name": "[debian-lts-announce] 20180718 [SECURITY] [DLA 1423-1] linux-4.9 new package",
          "refsource": "MLIST",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3753-1/",
          "name": "USN-3753-1",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3753-2/",
          "name": "USN-3753-2",
          "refsource": "UBUNTU",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bounds write and a denial of service or unspecified other impact is possible by mounting and operating a crafted ext4 filesystem image."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-07-26T18:29Z",
  "lastModifiedDate": "2018-08-24T10:29Z"
}